### 作業目的: 更加了解word2vec高速化
本次作業主要是幫同學更熟悉與了解透過各項技巧來加速word2vec的原理，同學可以參考章節講義來回答下列問題。

### Q1 - 請問word2vec原本的設計有何問題以及可以怎麼對相對應的問題做改善?


Answer:

1. 輸入層中，one-hot encode會佔據過多記憶體  
2. 字典很龐大時，矩陣運算會需要更多的計算資源與時間，最後的softmax輸出會隨著字典增加運算複雜度上升

### Q2 - 請問在Negative Sampling中的次方係數，會如何影響字詞的抽取?
Hint: 如何影響高頻詞與低頻詞的抽取機率

Answer:
1. 當次方縮小時，會使低頻詞被抽到的機率提升

In [11]:
import numpy as np
a = [15, 10, 2]
denominator1 = np.sum(a)
numerator = a

numerator2 = np.power(a, 0.75)
denominator2 = np.sum(numerator2)

numerator3 = np.power(a, 0.5)
denominator3 = np.sum(numerator3)

print(numerator/denominator1)
print(numerator2/denominator2)
print(numerator3/denominator3)

[0.55555556 0.37037037 0.07407407]
[0.51061101 0.37672265 0.11266635]
[0.45836973 0.37425731 0.16737296]
