### 作業目的: 更加熟習pytorch的tensor操作

pytorch中有提供很多的API，讓使用者針對tensor進行各式各樣的操作，本次的作業希望讀者由pytorch的[官方網站](https://pytorch.org/docs/stable/torch.html)中選定四個針對tensor操作的API，對他的使用方法進行範例操作演練。

### 選定的API 函數

**請寫下選定的API functions**

ex:
* torch.from_array() / tensor.numpy()
* torch.unsqueeze() / torch.squeeze()
* tensor.transpose() / tensor.permute()
* torch.reshape() / tensor.view()

In [2]:
# Import torch and other required modules
import torch
import numpy as np

### 範例:
### Function 1 - torch.from_array() / tensor.numpy()

In [3]:
# Example 1 - 將torch tensor與numpy ndarray互相轉換
a = np.random.rand(1,2,3,3)
print(f'a: {type(a)}, {a.dtype}')
b = torch.from_numpy(a)
print(f'b: {type(b)}, {b.dtype}')
c = torch.tensor(a)
print(f'c: {type(c)}, {c.dtype}')
d = c.numpy()
print(f'd: {type(d)}, {d.dtype}')

a: <class 'numpy.ndarray'>, float64
b: <class 'torch.Tensor'>, torch.float64
c: <class 'torch.Tensor'>, torch.float64
d: <class 'numpy.ndarray'>, float64


In [4]:
# Example 2 - 經過轉換後，torch tensor與numpy array依然有相近的資料型態
a = np.random.randint(low=0, high=10, size=(2,2))
print(f'a: {type(a)}, {a.dtype}')
b = torch.from_numpy(a)
print(f'b: {type(b)}, {b.dtype}')
c = torch.tensor(a)
print(f'c: {type(c)}, {c.dtype}')
d = c.numpy()
print(f'd: {type(d)}, {d.dtype}')

a: <class 'numpy.ndarray'>, int64
b: <class 'torch.Tensor'>, torch.int64
c: <class 'torch.Tensor'>, torch.int64
d: <class 'numpy.ndarray'>, int64


### Function 1 - torch.from_numpy() / tensor.numpy()/linspace()/logspace()

In [8]:
# Example 1 - 練習Numpy,torch.tensor互轉
### your code ###
a = np.array([1,2,3])
t1 = torch.from_numpy(a)
t2 = torch.tensor(a)
b = t2.numpy()
print("a: ",type(a),a.dtype)
print("t1: ",type(t),t.dtype)
print("t2: ",type(t),t.dtype)
print("b: ",type(t),t.dtype)

a:  <class 'numpy.ndarray'> int32
t1:  <class 'torch.Tensor'> torch.int32
t2:  <class 'torch.Tensor'> torch.int32
b:  <class 'torch.Tensor'> torch.int32


In [15]:
# Example 2 - 練習linspace,logspace
### your code ###
print(torch.linspace(3,10,steps=5))
print(torch.linspace(-10,10,steps=5))
print(torch.logspace(-10,10,steps=5))
print(torch.logspace(-10,10,steps=5,base=2))
print(torch.logspace(0.1,1,steps=5))

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])
tensor([-10.,  -5.,   0.,   5.,  10.])
tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])
tensor([9.7656e-04, 3.1250e-02, 1.0000e+00, 3.2000e+01, 1.0240e+03])
tensor([ 1.2589,  2.1135,  3.5481,  5.9566, 10.0000])


### Function 2 - torch.unsqueeze() / torch.squeeze()

In [26]:
# Example 1 - 練習unsqueeze，在給定的位置增加維度
### your code ###
a = torch.tensor([[[1, 2, 3], [3, 4, 5]],[[5, 6, 7], [7, 8, 9]]])
print(a)
print(a.shape)

b = torch.unsqueeze(a,dim=0)
print(b)
print(b.shape)

tensor([[[1, 2, 3],
         [3, 4, 5]],

        [[5, 6, 7],
         [7, 8, 9]]])
torch.Size([2, 2, 3])
tensor([[[[1, 2, 3],
          [3, 4, 5]],

         [[5, 6, 7],
          [7, 8, 9]]]])
torch.Size([1, 2, 2, 3])


In [34]:
# Example 2 - 練習squeeze
### your code ###
print(b.size())
c = torch.squeeze(b,0)
print(c.size())
d = torch.squeeze(b,1)
print(d.size())
e = torch.squeeze(b)
print(e.size())

torch.Size([1, 2, 2, 3])
torch.Size([2, 2, 3])
torch.Size([1, 2, 2, 3])
torch.Size([2, 2, 3])


### Function 3 - tensor.randn()/tensor.transpose() / tensor.permute()

In [13]:
# Example 1 - Transpose 維度對調
### your code ###

x = torch.randn(2,3) #產生2維，每維3元素的 2 * 3 矩陣
print(torch.transpose(x,0,1)) # 將第0維和第1維對調 變成 3 * 2的矩陣

y = torch.tensor([[[1, 2, 3], [3, 4, 5]],[[5, 6, 7], [7, 8, 9]]]) #產生一個 2*2*3矩陣
print()
print(y.shape)
print(torch.transpose(y,1,2).shape) #第一維與第二維對調 變成 2*3*2矩陣
print()
print(torch.transpose(y,1,2))

tensor([[0.5834, 0.0666],
        [1.9842, 0.9965],
        [0.0402, 1.1482]])

torch.Size([2, 2, 3])
torch.Size([2, 3, 2])

tensor([[[1, 3],
         [2, 4],
         [3, 5]],

        [[5, 7],
         [6, 8],
         [7, 9]]])


In [17]:
# Example 2 - permute給定維度輸出順序
### your code ###
x = torch.randn(2,3,5)
print(x.shape,"\n")
print(x.permute(2,0,1).shape)

torch.Size([2, 3, 5]) 

torch.Size([5, 2, 3])


### Function 4 - torch.reshape() / tensor.view()

In [22]:
# Example 1 - reshape 與 view 皆可以用來改變 tensor 的形狀
### your code ###
a = torch.tensor([[[1, 2, 3], [3, 4, 5]],
				 [[5, 6, 7], [7, 8, 9]]])
b = a.reshape(6,2)
print(b,"\n")
c = a.reshape(4,-1) #填寫-1會自動計算應該要有的維度
print(c,"\n")

tensor([[1, 2],
        [3, 3],
        [4, 5],
        [5, 6],
        [7, 7],
        [8, 9]]) 

tensor([[1, 2, 3],
        [3, 4, 5],
        [5, 6, 7],
        [7, 8, 9]]) 



In [23]:
# Example 2 - ### your explanation ###
### your code ###
e = a.view(2,6)
print(e)

tensor([[1, 2, 3, 3, 4, 5],
        [5, 6, 7, 7, 8, 9]])
